version: '3.8'

services:

  qms_spring:
    image: qms_spring
    ports:
      - 8081:8080
    env_file:
      - env-var-public
      - env-var-private
    depends_on:
      - qms_db

  qms_db:
    image: postgres:15.2
    ports:
      - 5432:5432
    env_file:
      - env-var-public
      - env-var-private
    volumes:
      - ./postgres-data:/var/lib/postgresql/data