package com.maksimzotov.queuemanagementsystemserver.message;

public enum Message {
    USERNAME_MUST_NOT_BE_EMPTY,
    USERNAME_MUST_CONTAINS_LESS_THAN_64_SYMBOLS,
    PASSWORD_MUST_CONTAINS_MORE_THAN_8_SYMBOLS,
    PASSWORD_MUST_CONTAINS_LESS_THAN_64_SYMBOLS,
    PASSWORDS_DO_NOT_MATCH,
    FIRST_NAME_MUST_NOT_BE_EMPTY,
    FIRST_NAME_MUST_CONTAINS_LESS_THAN_64_SYMBOLS,
    LAST_NAME_MUST_NOT_BE_EMPTY,
    LAST_NAME_MUST_CONTAINS_LESS_THAN_64_SYMBOLS,
    WRONG_EMAIL,
    USERNAME_RESERVED_START,
    USERNAME_RESERVED_END,
    USER_WITH_USERNAME_ALREADY_EXISTS_START,
    USER_WITH_USERNAME_ALREADY_EXISTS_END,
    USER_WITH_EMAIL_ALREADY_EXISTS_START,
    USER_WITH_EMAIL_ALREADY_EXISTS_END,
    CONFIRMATION_OF_REGISTRATION,
    CODE_FOR_CONFIRMATION_OF_REGISTRATION,
    CODE_MUST_CONTAINS_4_SYMBOLS,
    CODE_EXPIRED,
    USER_WITH_USERNAME_DOES_NOT_EXIST_START,
    USER_WITH_USERNAME_DOES_NOT_EXIST_END,
    WRONG_PASSWORD,
    AUTHORIZATION_FAILED,
    REFRESH_TOKEN_IS_MISSING
    ;

    public String toMessageId() {
        return name().toLowerCase();
    }
}
